score_thresholds:
  review: 0.45
  block: 0.75

hard_rules:
  max_payment_attempts: 5
  min_account_age_days: 2

monitoring:
  score_shift_alert: 0.15
  quality_drop_ratio_alert: 0.85
  latency_p95_ms_alert: 25.0
